## This content is duplicated here from configs/config_designers.yml because I'm building this site through Github Pages, and Github Pages just looks for the _config.yml file in the root directory to create the build.
# project definitions
project: doc_designers
audience: designers
product: all
platform: all
version: all
destination: ../doc_designers
baseurl: "/"
pagefileurl: "../../"
api_baseurl: "/api"
fileurl: "../"
url: "http://developers.iqmetrix.com/"
topnav_title: iQmetrix Developer Portal 
homepage_title: iQmetrix Developer Portal 
site_title: iQmetrix Developer Portal 
disqus_shortname: iqmetrixdeveloperportal
google_analytics: UA-69492-17
github_editme_path: 

sidebar_tagline: 
sidebar_version: 

port: 4006

exclude:
  - doc_writers*
  - configs/
  - _site
  - doc_multi*

# same for all
host: 127.0.0.1
feedback_email: apidesign@iqmetrix.com
sidebar_accordion: true
markdown: redcarpet
print: false
theme_file: theme-blue.css
# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true