## This content is duplicated here from configs/config_designers.yml because I'm building this site through Github Pages, and Github Pages just looks for the _config.yml file in the root directory to create the build.
# project definitions
project: POS Documentation
audience: POS Clients
product: POS
platform: all
version: all
destination: 
baseurl: 
pagefileurl:
api_baseurl: 
fileurl: 
url: 
topnav_title: iQmetrix POS 
homepage_title: iQmetrix POS
site_title: iQmetrix POS Documentation
disqus_shortname: 
google_analytics: 
github_editme_path: 

sidebar_tagline: 
sidebar_version: 

port: 4006

exclude:
  - doc_writers*
  - configs/
  - _site
  - doc_multi*
  - raml

# same for all
host: 127.0.0.1
feedback_email: 
sidebar_accordion: true
markdown: kramdown
print: false
theme_file: theme-blue.css
# only use suffix if you need to force index.html to display
# suffix: index.html

highlighter: rouge

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
