# mandatory definitions
project: documentation-theme-jekyll-writer

audience: writer

product: all

platform: all

version: all

topnav_title: Jekyll for writers

topnav_version: "2.0"

tagline: Guide for writers

baseurl: "/documentation-theme-jekyll/writer" 

port: 4008

destination: ../documentation-theme-jekyll-builds/writer

homepage_title: Doc theme for Jekyll -- writer version

site_title: Documentation theme for Jekyll -- designer version
