baseurl: "/documentation-theme-jekyll/designer-pdf"

host: 127.0.0.1

port: 4005 

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true


print: true
destination: ../documentation-theme-jekyll-builds/designer_guide.pdf